# Generated by Django 4.1.5 on 2023-01-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drvice',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('drvice_name', models.CharField(default='', max_length=100)),
                ('drvice_passwd', models.CharField(default='', max_length=100)),
                ('drvice_host', models.CharField(default='', max_length=100)),
                ('drvice_user', models.CharField(default='', max_length=100)),
                ('drvice_port', models.IntegerField(default=22)),
                ('drvice_type', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Drvice',
                'verbose_name_plural': 'Drvice',
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('drvice_type', models.CharField(max_length=10000)),
                ('script_name', models.CharField(max_length=100)),
                ('script_reson', models.CharField(max_length=10000)),
            ],
            options={
                'verbose_name': 'drvice_script',
                'verbose_name_plural': 'drvice_script',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('setting_name', models.CharField(default='', max_length=100)),
                ('setting_value', models.CharField(default='', max_length=1000)),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Setting',
            },
        ),
    ]
